# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 08:44
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titre')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenu')),
                ('example', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='(Facultatif) Vous pouvez ici saisir des exemples.', verbose_name='Exemple')),
                ('note', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='(Facultatif) Vous pouvez ici saisir des notes complémentaires.', verbose_name='Note')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('description', models.CharField(blank=True, max_length=254, verbose_name='Description')),
                ('views', models.IntegerField(default=0)),
                ('last_seen', models.DateTimeField()),
            ],
            options={
                'ordering': ['update_date', 'created_date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=50, verbose_name='Titre')),
                ('description', models.CharField(blank=True, max_length=254, verbose_name='Description')),
                ('views', models.IntegerField(default=0)),
                ('last_seen', models.DateTimeField()),
                ('discipline_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studhelpcore.Discipline', verbose_name='Discipline')),
            ],
            options={
                'ordering': ['update_date', 'created_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studhelpcore.Chapter')),
                ('document_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studhelpcore.Document')),
            ],
        ),
    ]
